<div class="container">
            	<div class="row" style="margin-top:3%;">
                	<div class="col-lg-6 col-md-6 col-sm-6 pull-left">
                    	<img src="assets/image/img-logo.png" class="img-responsive" />
                    </div>
                 
                </div>    
<header>
    <h1>You're almost ready to start selling!</h1>
</header>
<p>
    Thank you for signing up with PeoplePerHour! Please complete your application in order to join our community of the highest quality Freelancers online.</p>
<hr class="append-bottom">
<div class="panel-group" id="seller-application">
   <div class="panel panel-default">
        <div class="panel-heading header-collapsed">
            <h4 class="panel-title" >
                1 Tell Us About You
          
            </h4>
      
        </div>
 
       <form class="form-horizontal hourly" role="form" method="post" action="" name="hourly">
  <div class="form-group">
    <label for="job title" class="col-sm-2 control-label">Job Title</label>
    <div class="col-sm-5">
        <input type="text" class="form-control" id="jobtitle" placeholder="eg. Web developer" name="jobTitle">
    </div>
  </div>
  <div class="form-group">
    <label for="phonenumber" class="col-sm-2 control-label">Phone number</label>
    <div class="col-sm-5">
        <input type="text" class="form-control" id="phone" placeholder="phonenumber" name="phone">
    </div>
  </div>
   <div class="form-group">
    <label for="rate" class="col-sm-2 control-label">Rate per Hour</label>
    <div class="col-sm-2">
        <select class="form-control" name="currency">
            <option name="1" value="dollar">$</option>
            <option name="2" value="euro">&euro;</option>
            <option name="3" value="pound">&pound;</option>
            <option name="4">₹</option>
            
        </select>
    </div>
    <div class="col-sm-3">
        <input type="text" class="form-control" id="amount" placeholder="charge" name="rate">
    </div>
  </div>
   <div class="form-group">
    <label for="image" class="col-sm-2 control-label">Upload Image</label>        
                <div class="col-sm-2">
       <input required="true" id="imagefile" name="profileImage" type="file"/><br>
           <span id="errormsg"></span>
    </div>
   </div>
                
   <div class="form-group">
     <label class="col-sm-2 control-label" for="description">About You</label>
      <div class="col-sm-5">
           <textarea class="form-control" id="description" name="aboutYou"></textarea>
      </div>
   </div>
    <div class="form-group">
    <label for="portfolio" class="col-sm-2 control-label">Portfolio(Optional)</label>        
        <div class="col-sm-2">
       <input required="true" id="portfolio" name="portfolio" type="file"/><br>
        <span id="errormsg"></span>
    </div>
   </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-warning continue">Continue</button>
    </div>
  </div>
</form>
        </div>
   </div>
</div>
