	<body style="background-color:#f0f0ee;">
    	<div class="container" style="background-color:#FFF; margin-top:5%;">
        	
        		<div class="container-fixed">
					<div class="navbar-header">
                		<div align="left">
                	  		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
               	      			<span class="sr-only">Toggle navigation</span>
               	      			<span class="icon-bar"></span>
               	      			<span class="icon-bar"></span>
               	      			<span class="icon-bar"></span>
               	      		</button>
              	  		</div>
            		</div>
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        			</div>
        		</div>
    		</nav>
        
        	<div class="container">
            	<div class="row" style="margin-top:3%;">
                	<div class="col-lg-6 col-md-6 col-sm-6 pull-left">
                    	<img src="/assets/image/img-logo.png" class="img-responsive" />
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 pull-right" style="padding-right:5%;">
                    	<form class="navbar-form navbar-right" role="search">
							<div class="form-group search">
								<input type="text" class="form-control" name="search" placeholder="" style="border-radius:0px;" />
                            	<input type="submit" class="form-control" value=" " />
							</div>
						</form>
                    </div>
                </div>
                
                <div class="row" style="margin-top:5%;">
                	<div class="col-lg-12 col-md-12 col-sm-12">
                    	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  							<!-- Indicators -->
  							<ol class="carousel-indicators">
    							<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    							<li data-target="#carousel-example-generic" data-slide-to="1"></li>
    							<li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  							</ol>

  							<!-- Wrapper for slides -->
  							<div class="carousel-inner">
    							<div class="item active">
      								<img src="/assets/image/img-slider-pic1.png" class="img-thumbnail" alt="pic1" />
      								<div class="carousel-caption">
                                    
      								</div>
    							</div>
    							<div class="item">
      								<img src="/assets/image/img-slider-pic2.png" class="img-thumbnail" alt="pic2" />
      								<div class="carousel-caption">
                                    
        							</div>
      							</div>
                                <div class="item">
      								<img src="/assets/image/img-slider-pic3.png" class="img-thumbnail" alt="pic3" />
      								<div class="carousel-caption">
                                    
        							</div>
      							</div>
                                <div class="item">
      								<img src="/assets/image/img-slider-pic4.png" class="img-thumbnail" alt="pic4" />
      								<div class="carousel-caption">
                                    
        							</div>
      							</div>
                                <div class="item">
      								<img src="/assets/image/img-slider-pic5.png" class="img-thumbnail" alt="pic2" />
      								<div class="carousel-caption">
                                    
        							</div>
      							</div>
    						</div>
  						</div>

  						<!-- Controls -->
  						<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    						<span class="fa fa-chevron-left fa-2x" style="margin-top: 133%; margin-left: -33%; color:#ff7700;"></span>
  						</a>
  						<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    						<span class="fa fa-chevron-right fa-2x" style="margin-top: 133%; color:#ff7700;"></span>
  						</a>
                    </div>
                </div>
                
                <div class="row" style="margin-top:5%; width:100%;">
  					<div class="col-sm-3 col-md-3 col-lg-3">
    					<div class="thumbnail">
      						<img src="/assets/image/img-pf-pic1.png" alt="pic1">
      						<div class="caption">
        						<h4>WRITING & TRANSLATION</h4>
        						<p></p>
        						<p><a href="#" class="pull-right">more >></a></p><br>
     						</div>
    					</div>
  					</div>
                    <div class="col-sm-3 col-md-3 col-lg-3">
    					<div class="thumbnail">
      						<img src="/assets/image/img-pf-pic2.png" alt="pic2">
      						<div class="caption">
        						<h4>SOCIAL MEDIA</h4>
        						<p></p>
        						<p><a href="#" class="pull-right">more >></a></p><br>
     						</div>
    					</div>
  					</div>
                    <div class="col-sm-3 col-md-3 col-lg-3">
    					<div class="thumbnail">
      						<img src="/assets/image/img-pf-pic3.png" alt="pic3">
      						<div class="caption">
        						<h4>SALES & MARKETING</h4>
        						<p></p>
        						<p><a href="#" class="pull-right">more >></a></p><br>
     						</div>
    					</div>
  					</div>
                    <div class="col-sm-3 col-md-3 col-lg-3">
    					<div class="thumbnail">
      						<img src="/assets/image/img-pf-pic4.png" alt="pic4">
      						<div class="caption">
        						<h4>SOFTWARE DEVELOPMENT</h4>
        						<p></p>
        						<p><a href="#" class="pull-right">more >></a></p><br>
     						</div>
    					</div>
  					</div>
				</div>
                
                <div class="row" style="margin-top:3%;">
                	<div class="col-sm-12 col-md-12 col-lg-12 welcome_text">
                    	<div class="col-sm-3 col-md-3 col-lg-3" style="text-align: center; margin-top: 2%;">
                        	<h4>WELCOME !!!</h4>
                        </div>
                        <div class="col-sm-9 col-md-9 col-lg-9">
                        	<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
                        </div>
                    </div>
                </div>
                
                <div class="row" style="margin-top:5%;">
                	<div class="col-lg-3 col-md-3 col-sm-3">
                    	<label style="color:#ff7300;">CATEGORIES</label><br><br>
                        <ul class="list-unstyled">
                        	<li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Design</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Writing & Translation</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Video, Photo & Audio</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Business Support</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Social Media</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Sales & Marketing</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Software Development</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Mobile</a></li><br>
                            <li><span class="fa fa-angle-right"></span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Web Development</a></li><br>
                        </ul>
                    </div>
                    <div class="col-lg-9 col-md-9 col-sm-9">
                    	<label style="color:#ff7300;">RECENT POSTS</label><br><br>
                        <div class="col-sm-4 col-md-4 col-lg-4">
    						<div class="thumbnail">
      							<img src="/assets/image/img-pf-pic1.png" alt="pic1">
      							<div class="caption">
        							<h4>POST - I</h4>
        							<p></p>
        							<p><a href="#" class="pull-left btn btn-primary" role="button">APPLY</a></p><br><br>
     							</div>
    						</div>
  						</div>
                    	<div class="col-sm-4 col-md-4 col-lg-4">
    						<div class="thumbnail">
      							<img src="/assets/image/img-pf-pic2.png" alt="pic2">
      							<div class="caption">
        							<h4>POST - II</h4>
        							<p></p>
        							<p><a href="#" class="pull-left btn btn-primary" role="button">APPLY</a></p><br><br>
     							</div>
    						</div>
  						</div>
                    	<div class="col-sm-4 col-md-4 col-lg-4">
    						<div class="thumbnail">
      							<img src="/assets/image/img-pf-pic3.png" alt="pic3">
      							<div class="caption">
        							<h4>POST - III</h4>
        							<p></p>
        							<p><a href="#" class="pull-left btn btn-primary" role="button">APPLY</a></p><br><br>
     							</div>
    						</div>
  						</div>
                    	<div class="col-sm-4 col-md-4 col-lg-4">
    						<div class="thumbnail">
      							<img src="/assets/image/img-pf-pic4.png" alt="pic4">
      							<div class="caption">
        							<h4>POST - IV</h4>
        							<p></p>
        							<p><a href="#" class="pull-left btn btn-primary" role="button">APPLY</a></p><br><br>
     							</div>
    						</div>
  						</div>
                        <div class="col-sm-4 col-md-4 col-lg-4">
    						<div class="thumbnail">
      							<img src="/assets/image/img-pf-pic5.png" alt="pic5">
      							<div class="caption">
        							<h4>POST - V</h4>
        							<p></p>
        							<p><a href="#" class="pull-left btn btn-primary" role="button">APPLY</a></p><br><br>
     							</div>
    						</div>
  						</div>
                    	<div class="col-sm-4 col-md-4 col-lg-4">
    						<div class="thumbnail">
      							<img src="/assets/image/img-pf-pic6.png" alt="pic6">
      							<div class="caption">
        							<h4>POST - VI</h4>
        							<p></p>
        							<p><a href="#" class="pull-left btn btn-primary" role="button">APPLY</a></p><br><br>
     							</div>
    						</div>
  						</div>
                    </div>
                </div>               
            </div>
            </div>
	</body>

