<div class="container">
            	<div class="row" style="margin-top:3%;">
                	<div class="col-lg-6 col-md-6 col-sm-6 pull-left">
                    	<img src="/assets/image/img-logo.png" class="img-responsive" />
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 pull-right" style="padding-right:5%;">
                    	
                    </div>
                </div>
<div class="row" style="margin-top:5%;">
                	<div class="col-sm-12 col-md-12 col-lg-12" style="text-align:center;">
                    	<h1>Sign Up</h1>
                        <p style="color:#ccc;">Already have an account? <b><a data-toggle="modal" href="#myModal">Log In</a></b></p><br>
                   	</div>
                    <div class="col-sm-8 col-md-8 col-lg-8 clearfix pull-right" style="margin-right:-1%;">
                    	<div class="col-lg-12">
                        	<img src="/assets/image/img-fb.png" /> &nbsp;&nbsp; <img src="/assets/image/img-linkedin.png" />
                        </div>
                        <div class="col-lg-12">
                        	<hr style="color:#ccc;  width: 44%;" class="pull-left">
                        </div><br><br>
                        <div class="col-lg-12">
                    		<form class="signupform" role="form" method="POST" action="" id="form">
                            	<div class="col-sm-12 col-md-12 col-lg-12" style="margin-left:-3%;">
                            		<div class="col-md-3">
                            			<label>First Name</label><br>
                            			<input type="text" class="form-horizontal" name="firstName" />
                                	</div>
                                	<div class="col-md-3">
                                		<label>Last Name</label><br>
                                		<input type="text" class="form-horizontal" name="lastName" /><br><br>
                                	</div>
                            	</div>
                                <div class="col-sm-12 col-md-12 col-lg-12" style="margin-left:-3%;">
                                	<div class="col-md-6">
                                    	<label>Email Address</label><br>
                            			<input type="text" class="form-group" name="email" /><br><br>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12" style="margin-left:-3%;">
                                	<div class="col-md-6">
                                    	<label>Password</label><br>
                            			<input type="password" class="form-group" name="password" /><br><br>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12" style="margin-left:-3%;">
                                	<div class="col-md-6">
                                    	<label>Location</label><br>
                            			<input type="text" class="form-group" name="location" /><br><br>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12" style="margin-left:-3%;">
                                	<div class="col-md-12">
                                    	<label>What are you looking for?</label><br>
                                      
<input type="radio" class="btn btn-primary" name="services"   value="0"/>&nbsp;&nbsp;&nbsp;Buy&nbsp;&nbsp;&nbsp;
<input type="radio" class="btn btn-primary" name="services"   value="1"/>&nbsp;&nbsp;&nbsp;Sell&nbsp;&nbsp;&nbsp;
<input type="radio" class="btn btn-primary" name="services"   value="2"/>&nbsp;&nbsp;&nbsp;Both&nbsp;&nbsp;&nbsp;

                            			
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12" style="margin-left:-3%;">
                                	<br><button class="btn btn-info col-lg-6">Sign Up</button><br><br><br><br><br><br>
                                </div>
                        	</form>
                        </div>
                    </div>
                </div>	
</div>