<div class="container">
            	<div class="row" style="margin-top:3%;">
                	<div class="col-lg-6 col-md-6 col-sm-6 pull-left">
                    	<img src="assets/image/img-logo.png" class="img-responsive" />
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 pull-right" style="padding-right:5%;">
                    	<form class="navbar-form navbar-right" role="search">
							<div class="form-group search">
								<input type="text" class="form-control" name="search" placeholder="" style="border-radius:0px;" />
                            	<input type="submit" class="form-control" value=" " />
							</div>
						</form>
                    </div>
                </div>
                
                <div class="row" style="margin:5% 4% 3% 1%; background-color:#f0f0ee; padding-top:2%; padding-bottom:2%;">
                	<div class="col-lg-3 col-md-3 col-sm-3">
                    	<div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                    	<div class="btn-group" style="text-align: -moz-left !important; ">
  							<button id="dropdownMenu1" type="button" style="color:#ff7300;" class="btn fa fa-list fa-lg dropdown-toggle" data-toggle="dropdown">
                           	</button> &nbsp; <label style="margin-top:9px;">CATEGORIES</label>
                        	<ul class="dropdown-menu pull-left mega-menu">
   								<li class="mega-menu-column">
						    		<ul>
						        		<li class="nav-header">ALL CATEGORIES</li>
						        			<img src="/assets/image/img-mega-cate.png" class="img-thumbnail" />
										<li><a href="#">Design</a></li>
						        		<li><a href="#">Writing & Translation</a></li>
						        		<li><a href="#">Video, Photo & Audio</a></li>
						        		<li><a href="#">Business Support</a></li>
						        		<li><a href="#">Social Media</a></li>
						        		<li><a href="#">Sales & Marketing</a></li>
                                        <li><a href="#">Software Development</a></li>
                                        <li><a href="#">Mobile</a></li>
                                        <li><a href="#">Web Development</a></li>
						    		</ul>
						    	</li>    
        
						    	<li class="mega-menu-column">
						    		<ul>
						    			<li class="nav-header">POPULAR SKILLS</li>
						        			<img src="assets/image/img-mega-pskills.png" class="img-thumbnail" />
										<li><a href="#">design &nbsp;&nbsp;&nbsp;&nbsp;</a></li>
						        		<li><a href="#">web development</a></li>
						        		<li><a href="#">web design</a></li>
						        		<li><a href="#">identity design&nbsp;&nbsp;&nbsp;</a></li>
						        		<li><a href="#">seo &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
						        		<li><a href="#">business support</a></li>
										<li><a href="#">writing</a></li>
						        		<li><a href="#">wordpress</a></li>
						        		<li><a href="#">logo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
						        		<li><a href="#">video, photo & audio</a></li>
						        		<li><a href="#">search marketing</a></li>
						        		<li><a href="#">social media marketing</a></li>
										<li><a href="#">web writing</a></li>
						        		<li><a href="#">graphic design</a></li>
						        		<li><a href="#">html&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
						        		<li><a href="#">marketing pr</a></li>
						        		<li><a href="#">social media</a></li>
						        		<li><a href="#">article</a></li>
                                        <li><a href="#">illustration</a></li>
						        		<li><a href="#">blog writing</a></li>
						        		<li><a href="#">css&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></a></li>
						        		<li><a href="#">photoshop</a></li>
						    		</ul>
						    	</li>
                           	</ul>
						</div>
                        </div><br><br>
                        <div class="col-lg-12 col-md-12 col-sm-12" style="background-color:#d7d7d7; padding:16% 7% 7%; margin-left:7%;">
                        	<div class="row">
                        		<div class="col-lg-12 col-md-12 col-sm-12">
                        			<center><label style="font-size:20px; color:#ff7700;">Buyer Tips<br></label></center>
                                	<div class="col-lg-12 col-md-12 col-sm-12" style="padding:10%;">
                                        <div class="divider"></div><br>
                                        <p><br><br><img src="assets/image/img-step-1.png" class="img-responsive pull-left" /><br><br></p>
                                        <p>Post your job for free specifying what you need Done..<br><br></p>
                                        <p><br><br><img src="assets/image/img-step-2.png" class="img-responsive pull-left" /><br><br></p>
                                        <p>Receive Proposals from quality Freelancers and chat with them..<br><br></p>
                                        <p><br><br><img src="assets/image/img-step-3.png" class="img-responsive pull-left" /><br><br></p>
                                        <p>Select your Freelancers based on their profile and feedback..<br><br></p>
                                        <p><br><br><img src="assets/image/img-step-4.png" class="img-responsive pull-left" /><br><br></p>
                                        <p>Pay only if satisfied with the work delivered..<br><br></p>
                                    </div>
                                <br><br>                                	
                        		</div>
                        	</div>
                        </div>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9 col-sm-9">
                    	<div class="row">
                        	<div class="col-lg-12 col-md-12 col-sm-12" style="margin-left: 4%; margin-top: 2px;">
                        		<label style="font-size:20px;">Post a Job</label>
                            </div><br>
                            <div class="col-lg-12 col-md-12 col-sm-12" style="background-color:#FFF;  margin-left: 5%; margin-top: 3px; width: 93%; padding-top:5%;">
                            	<form class="form-group" action="" name="post">
                            	<div class="col-sm-12 col-md-12 col-lg-12">
    								<h3>Get your Job Done!</h3><br>
                                    <p>Post a Job for Free - Start receiving proposals within minutes<br><br></p>
  								</div>
                    			<div class="col-sm-12 col-md-12 col-lg-12">
    								<label style="color:#ff7700;"><br>What do you need to get done?</label><br>
                                    <input type="text" class="form-control" name="ques1" style="width:47%;" />	
  								</div>
                    			<div class="col-sm-12 col-md-12 col-lg-12">
    								<label style="color:#ff7700;"><br><br>Pick Category</label><br>
                                    <select class="form-control" name="ques2"  style="width:30%;">
                                    	<option name="1">1</option>
                                        <option name="2">2</option>
                                        <option name="3">3</option>
                                        <option name="4">4</option>
                                        <option name="5">5</option>
                                 	</select><br>
                                    <select class="form-control" name="ques3"  style="width:30%;">
                                    	<option name="1">001</option>
                                        <option name="2">002</option>
                                        <option name="3">003</option>
                                        <option name="4">004</option>
                                        <option name="5">005</option>
                                 	</select>
  								</div>
                                <div class="col-sm-12 col-md-12 col-lg-12">
    								<label style="color:#ff7700;"><br><br>Description</label><br>
                                    <textarea rows="7" class="form-control" name="ques4"></textarea>
  								</div>
                    			<div class="col-sm-12 col-md-12 col-lg-12">
    								<label style="color:#ff7700;"><br><br>Upload samples and other helpful material (optional)</label><br>
                                    <textarea rows="7" class="form-control" name="ques5"></textarea>
  								</div>
                    			<div class="col-sm-12 col-md-12 col-lg-12">
    								<label style="color:#ff7700;"><br><br>Expected budget </label><br>
                                    <select class="form-horizontal" name="ques6"  style="width:30%;">
                                    	<option name="1">---Fixed Price---</option>
                                        <option name="2">A</option>
                                        <option name="3">B</option>
                                        <option name="4">C</option>
                                        <option name="5">D</option>
                                 	</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <select class="form-horizontal" name="ques7"  style="width:5%;">
                                    	<option name="1">$</option>
                                        <option name="2">&euro;</option>
                                        <option name="3">&pound;</option>
                                        <option name="4">₹</option>
                                 	</select>
                                    <input type="text" class="form-horizontal" name="ques1" style="width:34%;" />
  								</div>
                                <div class="col-sm-12 col-md-12 col-lg-12">
    								<label data-toggle="collapse" data-target="#demo" style="color:#ff7700; text-decoration:underline; cursor:pointer;"><br><br>+ Show advanced options (Deadline, location, interview questions)<br><br> </label><br>
                                    
                                    <div id="demo" class="collapse out">
                                        <div class="col-sm-12 col-md-12 col-lg-12">
    										<label style="color:#ff7700;"><br><br>Estimated deadline in (optional) </label><br>
                                   			<select class="form-horizontal" name="ques6"  style="width:30%;">
                                    			<option name="1">---Fixed Price---</option>
                                        		<option name="2">A</option>
                                        		<option name="3">B</option>
                                        		<option name="4">C</option>
                                        		<option name="5">D</option>
                                 			</select>
                                  		</div>
                                    	 <div class="col-sm-12 col-md-12 col-lg-12">
    										<label style="color:#ff7700;"><br><br>Get to know your Freelancer (optional) </label><br>
                                   			<select class="form-horizontal" name="ques6"  style="width:30%;">
                                    			<option name="1">---Fixed Price---</option>
                                        		<option name="2">1</option>
                                        		<option name="3">2</option>
                                        		<option name="4">3</option>
                                        		<option name="5">4</option>
                                 			</select><br><br>
                                  		</div>
                                        <div class="col-sm-12 col-md-12 col-lg-12">
    										<label style="color:#ff7700;"><br>Where does the Freelancer need to work from?</label><br>
                                            <input type="radio" class="form-horizontal" name="r1" />&nbsp;&nbsp;&nbsp;  Remotely from <br>
                                    		<input type="text" class="form-control" name="ques1"  style="width:47%;" />	<br>
  										</div>
                                        <div class="col-sm-12 col-md-12 col-lg-12">
    										<input type="radio" class="form-horizontal" name="r2" />&nbsp;&nbsp;&nbsp;  Come on-site in <br>
                                    		<input type="text" class="form-control" name="ques1"  style="width:47%;" /><br><br><br>
  										</div> 
									</div>                                        
  								</div>
                                </form>
                                <div class="col-sm-12 col-md-12 col-lg-12">
                                	<button class="btn btn-primary pull-right" data-toggle="modal" data-target=".bs-example-modal-lg">POST JOB</button>

<div aria-hidden="false" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1" class="modal fade bs-example-modal-lg in">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 id="myLargeModalLabel" class="modal-title">JOB POSTED SUCCESSFULLY</h4>
        </div>
        <div class="modal-body">
          <p>Thank You so much for Posting a Job - PeoplePerHour.com</p>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div>
                                    </div>
                                    
                                
                                <div class="col-sm-12 col-md-12 col-lg-12" style="text-align:center;">
                                	<center><img src="assets/image/img-post-pic.png" class="img-responsive" /></center><br><br><br>
                                </div>
                                
                                
                                
                                
                            </div>
                        </div>
                    </div>
             	</div>
        	</div>
            
     	</div>